<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	
	<title>Currency Converter</title>
	
	<!-- Stylesheets -->
	<?php 
		$this->headLink()->appendStylesheet('css/bootstrap.min.css');
		$this->headLink()->appendStylesheet('css/font-awesome.min.css');
		$this->headLink()->appendStylesheet('css/select2.css');
		$this->headLink()->appendStylesheet('css/noty.css');
		$this->headLink()->appendStylesheet('css/style.css');
		
		echo $this->headLink();
	?>
</head>

<body>
	<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
		<div class="navbar-container container-fluid">
			<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
				<i class="fa fa-exchange"></i>
			</div>
		</div>
	</nav>
	
	<div class="container center-contain">
		<div class="row center-screen">
			<div class="panel">
				<div class="panel-body">
					<div class="row row-lg">
						<div class="col-lg-12">
							<div class="exchange-text">
								<div class="exchange-title">
									<span id="value-from"><?php echo $this->escape($this->exchange['from_value']); ?></span> <span class="currency-from exchange-title-currency"><?php echo $this->escape($this->exchange['from_currency']); ?></span>  =  <span id="value-to"><?php echo $this->escape($this->exchange['to_value']); ?></span> <span class="currency-to exchange-title-currency"><?php echo $this->escape($this->exchange['to_currency']); ?></span>
								</div>
							</div>
							
							<div class="form-inline currency-control">
								<input type="text" name="value" id="value" class="form-control currency-value" value="1"/>
								
								<select id="select-from" class="currency-select">
									<?php foreach($this->currencies as $currency) { ?>
									<option value="<?php echo $this->escape($currency->getCode()); ?>"<?php echo $currency->getCode() == "USD" ? " selected" : "" ?>><?php echo $this->escape($currency->getCode())." - ".$this->escape($currency->getDescription()); ?></option>
									<?php } ?>
								</select>
								
								<button id="swap" type="button" class="btn btn-icon btn-default"><i class="fa fa-exchange"></i></button>
							
								<select id="select-to" class="currency-select">
									<?php foreach($this->currencies as $currency) { ?>
									<option value="<?php echo $this->escape($currency->getCode()); ?>"<?php echo $currency->getCode() == "EUR" ? " selected" : "" ?>><?php echo $this->escape($currency->getCode())." - ".$this->escape($currency->getDescription()); ?></option>
									<?php } ?>
								</select>
							
								<button id="convert" type="button" class="btn btn-icon btn-primary"><i id="arrow" class="fa fa-arrow-right"></i> <i id="preloader" class="fa fa-refresh fa-spin fa-fw" style="display:none"></i></button>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	
	<?php
		$this->InlineScript()->appendFile('js/jquery-1.9.1.min.js', 'text/javascript');
		$this->InlineScript()->appendFile('js/bootstrap.min.js', 'text/javascript');
		$this->InlineScript()->appendFile('js/select2.min.js', 'text/javascript');
		$this->InlineScript()->appendFile('js/noty.min.js', 'text/javascript');
		echo $this->InlineScript();
	?>
	<script type="text/javascript">
		$(document).ready(function() {
		  $(".currency-select").select2({ width: 'resolve' });
		});
		
		function exchange(from_currency, to_currency, value){
			if($.isNumeric(value)){
				if(from_currency && to_currency){
					$("#arrow").hide();
					$("#preloader").show();
					
					var base_url = '<?php echo $this->url(array("action" => "exchange", "controller" => "api"), "default", true); ?>';
					
					$.getJSON(base_url + '/from/'+from_currency+'/to/'+to_currency+'/value/'+value, function(data){
						if(data.error){
							new Noty({text: data.error, type: 'error', timeout: 5000, theme: 'mint'}).show();
						}
						else{
							var html = '<div class="exchange-title">' + $(".exchange-title").html() + '</div>';
							
							var old = $(".exchange-title");
							old.addClass('exchange-title-small');
							old.removeClass("exchange-title");
							old.before(html);
							
							$(".exchange-title #value-from").html(data.from_value);
							$(".exchange-title .currency-from").html(data.from_currency);
							$(".exchange-title #value-to").html(data.to_value);
							$(".exchange-title .currency-to").html(data.to_currency);
						}
					}).always(function(){
						$("#preloader").hide();
						$("#arrow").show();
					});
				}
				else{
					new Noty({text: 'Please select a valid currency', type: 'error', timeout: 5000, theme: 'mint'}).show();
				}
			}
			else{
				new Noty({text: 'Please enter a valid currency value', type: 'error', timeout: 5000, theme: 'mint'}).show();
			}
		}
		
		$(document).on('click', '#convert', function(e){
			var from_currency = $("#select-from").val();
			var to_currency = $("#select-to").val();
			var value = $("#value").val();
			
			exchange(from_currency, to_currency, value);
		});
		
		$(document).on('click', "#swap", function(e){
			var to_currency = $("#select-from").val();
			var from_currency = $("#select-to").val();
			var value = $("#value").val();
			$("#select-from").val(from_currency).trigger('change');
			$("#select-to").val(to_currency).trigger('change');
			
			exchange(from_currency, to_currency, value);
		});
	</script>
</body>
</html>